#magnus
version: '3'
services:


  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    volumes:
      - "/docker/appdata/nginx-proxy-manager:/config:rw"
    ports:
      - "8000:8181"
      - "80:8080" # first port is on localhost, second is on the docker container
      - "443:4443"

  # traefik:
  #   image: traefik:latest
  #   container_name: traefik
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"

      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer:/data
    restart: unless-stopped
    ports:
      - "8001:9000"


  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8002:8123

  tetris:
    image: ociotec/tetris
    ports:
      - 8003:80
